/**
 * CareTip — small blurb + "AI suggestion" tag explaining the user can
 * edit the schedule. Shows a tasteful fallback when no tip is available.
 */
interface CareTipProps {
  careTip?: string | null;
  /** "generating" → small inline loader; "missing" → fallback copy. */
  status?: "generating" | "ready" | "missing";
}

export default function CareTip({ careTip, status = "ready" }: CareTipProps) {
  if (status === "generating") {
    return (
      <div className="rounded-lg border border-stone-200 bg-stone-50 p-3 text-sm text-stone-600">
        <span className="inline-block animate-pulse">Generating schedule…</span>
      </div>
    );
  }

  const text =
    (careTip && careTip.trim()) ||
    (status === "missing"
      ? "Water when the top inch of soil is dry."
      : "Tap a rule below to tune the cadence.");

  return (
    <div className="relative rounded-lg border border-stone-200 bg-white p-3 text-sm text-stone-700">
      <p className="pr-16">{text}</p>
      <span
        className="absolute right-2 top-2 rounded-full border border-stone-300 bg-stone-50 px-2 py-0.5 text-[10px] uppercase tracking-wide text-stone-500"
        title="Generated by AI — tap the rules below to adjust cadences."
      >
        AI suggestion
      </span>
    </div>
  );
}
